-- Setup script for initial database configuration
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Create application user
CREATE USERS erms_user IDENTIFIED BY erms_password
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

-- Grant necessary privileges
GRANT CREATE SESSION TO erms_user;
GRANT CREATE TABLE TO erms_user;
GRANT CREATE VIEW TO erms_user;
GRANT CREATE SEQUENCE TO erms_user;
GRANT CREATE PROCEDURE TO erms_user;
GRANT CREATE TRIGGER TO erms_user;
GRANT UNLIMITED TABLESPACE TO erms_user;
GRANT CREATE ANY INDEX TO erms_user;
GRANT ALTER ANY INDEX TO erms_user;
GRANT DROP ANY INDEX TO erms_user;
GRANT SELECT ANY TABLE TO erms_user;
GRANT INSERT ANY TABLE TO erms_user;
GRANT UPDATE ANY TABLE TO erms_user;
GRANT DELETE ANY TABLE TO erms_user;

CREATE SEQUENCE EMPLOYEE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;